print('+----------------------------------------------------------+')
print('|KUIS MATEMATIKA(ILMU YANG MEMATIKAN)REMASTERED VERSION >:D|')
print('+---------------------------------------------------------`-+')
x = int(input('Masukan nilai X : '))
y = int(input('Masukan nilai Y : '))
z = int(input('Masukan nilai Z : '))
t = int(input('Masukan nilai T : '))
print('----------------------------------------')
key_answer = (x * y) - (z / t);
print('Berapakah (X * Y) - (Z / T) ? ')
answer  = int(input('Jawaban = '))
correction = key_answer == answer;
print('========================================')
print('Apakah jawaban anda benar :D? => ', correction)
print('========================================')
print('jawaban aslinya adalah ', key_answer)
print('')
print('')
print('=========================================================================================')
print('')
print('CONGRATS YOU HAVE GRADUATE MATH MASSACRE :D note : if you get it false you didnt graduate')
print('                    CREDIT                        ')
print('      programmer : Edward                         ')
print('      test bunny : my sister                      ')
print(" note : there is no test bunny harmed during making of this program")
print('             coming soon alot harder challenge only for the people who is brave enough')
print('')
print('=========================================================================================')
