a = 6;
b = 7;
c = a + b;
d = 4;
e = 9;
f = d - e;
g = 34;
h = 47;
i = g * h;
j = 345;
k = 5;
l = j / k;
megalodon = 56894;
qwer = 858493;
oof = megalodon * qwer;
blox = 35**2;
esc = 2**567;
yuip = 2*5;
hjkl = 3*7;
cvbn = yuip + hjkl;
altf4 = blox * esc;
asddf = altf4 + cvbn + oof;
pangkat1 = 23**3;
pangkat2 = 45**6;
pangkat3 = pangkat2 - pangkat1;
print(c);
print(f);
print(i);
print(l);
print(oof);
print(altf4);
print(cvbn);
print(asddf);
print(pangkat3);
